### ISSUE TITLE
Your SpeedE is skid! copy from ACB(AdvancedCheatBlocker)

### ISSUE THREAD

**Issue by BaGuAr** [OMGPandaYT/AxolotlCheatDetector#8]
ACB's github or spgiot is gone. but (github) forks is still! 
Your SpeedE code very looks like ACB's SpeedH. ( in The fork, SpeedH is old version. but It's good to work for proof. ) 
and I have latest of ACB ( latest Public version ) cuz I downloaded it long time ago!  
and I decompile acb, SpeedH is very looks like your speedeE and the latest version release is over few month ago. but Your SpeedE added 9 Aug and ACB's SpeedH is older than it!  NICE SKID.

**Comment by BaGuAr** [comment]
latest SpeedE is skid but older than it is not skid.

**Comment by t0206** [comment]
Hello jxy(omgpandayt).
I accept to use my speedH(SpeedE in your ac)
I hope you'll add 'Made by t0206'

Thanks for using my speed h check!

**Comment by OMGPandaYT** [comment]
@t0206 i noticed it was pretty good so i used it but forgot to put the credits, they are now there. thank you
